name: Mirror Forked PR for Preview
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  mirror-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create mirrored branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout -b pr-${{ github.event.pull_request.number }}
          git push origin pr-${{ github.event.pull_request.number }}
